server:
  host: localhost
  port: 8081
spring:
  rabbitmq:
    host: localhost
  freemarker:
    cache: false
#  devtools:
#    restart:
#      exclude: static/**,public/**,templates/**
bustracker:
  exchange-name: BUS_LOCATION
  location-update-interval: 1000
  session-timeout: 300
  route-settings:
    -
      id: 1
      route-file-name: route/1.gpx
      speed: 0.044
      time-zero: 0
      time-stop-at-station: 7
      min-distance-between-station: 0.5
      enabled: true
    -
      id: 2
      route-file-name: route/2.gpx
      speed: 0.039
      time-zero: 0
      time-stop-at-station: 10
      min-distance-between-station: 0.5
      enabled: true
    -
      id: 3
      route-file-name: route/3.gpx
      speed: 0.0239
      time-zero: 0
      time-stop-at-station: 5
      min-distance-between-station: 0.5
      enabled: true
    -
      id: 4
      route-file-name: route/4.gpx
      speed: 0.019
      time-zero: 0
      time-stop-at-station: 6
      min-distance-between-station: 0.35
      enabled: true
    -
      id: 5
      route-file-name: route/5.gpx
      speed: 0.0279
      time-zero: 0
      time-stop-at-station: 8
      min-distance-between-station: 0.45
      enabled: true
    -
      id: 6
      route-file-name: route/6.gpx
      speed: 0.055
      time-zero: 0
      time-stop-at-station: 4
      min-distance-between-station: 1.0
      enabled: true
    -
      id: 7
      route-file-name: route/7.gpx
      speed: 0.017
      time-zero: 0
      time-stop-at-station: 5
      min-distance-between-station: 0.6
      enabled: true
    -
      id: 8
      route-file-name: route/8.gpx
      speed: 0.023
      time-zero: 0
      time-stop-at-station: 6
      min-distance-between-station: 0.5
      enabled: true
