server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
  freemarker:
    cache: false
#  devtools:
#    restart:
#      exclude: static/**,public/**,templates/**
bustracker:
  exchange-name: BUS_LOCATION
  location-update-interval: 1000
  session-timeout: 300
  route-settings:
    -
      id: 1
      route-file-name: route/1.gpx
      speed: 0.044
      time-zero: 0
      time-stop-at-station: 10
      min-distance-between-station: 0.5
      enabled: true
    -
      id: 2
      route-file-name: route/2.gpx
      speed: 0.039
      time-zero: 0
      time-stop-at-station: 10
      min-distance-between-station: 0.5
      enabled: true


